Fix error in release_gem [ci skip]
https://github.com/sue445/rubocop-isucon/actions/runs/19794388983/job/56712575265

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/home/runner/work/rubocop-isucon/rubocop-isucon/vendor/bundle/ruby/3.4.0/gems/gda-1.1.5/ext/gda
/opt/hostedtoolcache/Ruby/3.4.3/x64/bin/ruby extconf.rb
checking for pkg-config for libgda-5.0... not found
checking for libgda/sql-parser/gda-sql-parser.h... no
checking for pkg-config for libgda-6.0... not found
checking for libgda/sql-parser/gda-sql-parser.h... no
libgda is missing. Try 'brew install pkg-config libgda' if you are on OSX and
have homebrew installed.
You can also check https://github.com/GNOME/libgda for more info on how to
install
the dependency.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include=${opt-dir}/include
	--without-opt-include
	--with-opt-lib=${opt-dir}/lib
	--without-opt-lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/hostedtoolcache/Ruby/3.4.3/x64/bin/$(RUBY_BASE_NAME)
	--with-libgda-dir
	--without-libgda-dir
	--with-libgda-include=${libgda-dir}/include
	--without-libgda-include
	--with-libgda-lib=${libgda-dir}/lib
	--without-libgda-lib
	--with-libgda-5.0-dir
	--without-libgda-5.0-dir
	--with-libgda-5.0-include=${libgda-5.0-dir}/include
	--without-libgda-5.0-include
	--with-libgda-5.0-lib=${libgda-5.0-dir}/lib
	--without-libgda-5.0-lib
	--with-libgda-5.0-config
	--without-libgda-5.0-config
	--with-pkg-config
	--without-pkg-config
	--with-libgda-6.0-dir
	--without-libgda-6.0-dir
	--with-libgda-6.0-include=${libgda-6.0-dir}/include
	--without-libgda-6.0-include
	--with-libgda-6.0-lib=${libgda-6.0-dir}/lib
	--without-libgda-6.0-lib
	--with-libgda-6.0-config
	--without-libgda-6.0-config
To see why this extension failed to compile, please check the mkmf.log which can
be found here:
/home/runner/work/rubocop-isucon/rubocop-isucon/vendor/bundle/ruby/3.4.0/extensions/x86_64-linux/3.4.0/gda-1.1.5/mkmf.log
extconf failed, exit code 1
Gem files will remain installed in
/home/runner/work/rubocop-isucon/rubocop-isucon/vendor/bundle/ruby/3.4.0/gems/gda-1.1.5
for inspection.
Results logged to
/home/runner/work/rubocop-isucon/rubocop-isucon/vendor/bundle/ruby/3.4.0/extensions/x86_64-linux/3.4.0/gda-1.1.5/gem_make.out
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/ext/builder.rb:126:in
'Gem::Ext::Builder.run'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/ext/ext_conf_builder.rb:30:in
'Gem::Ext::ExtConfBuilder.build'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/ext/builder.rb:195:in
'Gem::Ext::Builder#build_extension'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/ext/builder.rb:229:in
'block in Gem::Ext::Builder#build_extensions'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/ext/builder.rb:226:in
'Array#each'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/ext/builder.rb:226:in
'Gem::Ext::Builder#build_extensions'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/installer.rb:844:in
'Gem::Installer#build_extensions'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/rubygems_gem_installer.rb:111:in
'Bundler::RubyGemsGemInstaller#build_extensions'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/rubygems_gem_installer.rb:30:in
'Bundler::RubyGemsGemInstaller#install'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/source/rubygems.rb:220:in
'Bundler::Source::Rubygems#install'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/installer/gem_installer.rb:55:in
'Bundler::GemInstaller#install'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/installer/gem_installer.rb:17:in
'Bundler::GemInstaller#install_from_spec'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/installer/parallel_installer.rb:133:in
'Bundler::ParallelInstaller#do_install'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/installer/parallel_installer.rb:124:in
'block in Bundler::ParallelInstaller#worker_pool'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/worker.rb:62:in
'Bundler::Worker#apply_func'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/worker.rb:57:in
'block in Bundler::Worker#process_queue'
  <internal:kernel>:168:in 'Kernel#loop'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/worker.rb:54:in
'Bundler::Worker#process_queue'
/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/bundler/worker.rb:90:in
'block (2 levels) in Bundler::Worker#create_threads'
An error occurred while installing gda (1.1.5), and Bundler cannot continue.
In Gemfile:
  rubocop-isucon was resolved to 2.0.2, which depends on
    gda
Error: The process '/opt/hostedtoolcache/Ruby/3.4.3/x64/bin/bundle' failed with exit code 5
```